# Contiki network configuration
MAKE_NET = MAKE_NET_NULLNET

CONTIKI_PROJECT = clicker-ng
all: $(CONTIKI_PROJECT)

CONTIKI = $(HOME)/projects/course_wireless/contiki-ng

include $(CONTIKI)/Makefile.include
