
MAKE_NET = MAKE_NET_IPV6
MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC

CONTIKI_PROJECT = Lab3Task2
all: $(CONTIKI_PROJECT)

CONTIKI = $(HOME)/projects/course_wireless/contiki-ng

include $(CONTIKI)/Makefile.include
