MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET
CONTIKI_PROJECT = basestation intruder test-tmp login
APPS=serial-shell
all: $(CONTIKI_PROJECT)
CONTIKI = /home/felix/1-Projects/course_wireless/contiki-ng
include $(CONTIKI)/Makefile.include
